name: Update Readme Stats

on:
  schedule:
    - cron: "0 0 * * *" # 每天半夜运行一次
  workflow_dispatch: # 允许手动点击运行

jobs:
  download-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download Images
        run: |
          # 1. 下载主统计图 (注意：这里使用 curl 从 Vercel 接口拉取 SVG 并保存为本地文件)
          curl "https://github-readme-stats.vercel.app/api?username=JuyaoHuang&show_icons=true&theme=synthwave" -o github-stats.svg
          
          # 2. 下载语言统计图
          curl "https://github-readme-stats.vercel.app/api/top-langs/?username=JuyaoHuang&size_weight=0.5&count_weight=0.5&layout=compact&theme=synthwave" -o top-langs.svg

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # 检查是否有变化，有变化才提交
          if [[ -n $(git status -s) ]]; then
            git add github-stats.svg top-langs.svg
            git commit -m "Update GitHub Stats images"
            git push
          else
            echo "No changes found"
          fi
